### ISSUE TITLE
Pgmodeler 0.8.0

### ISSUE THREAD

**Issue by elidorio** [Hubbitus/Fedora-packaging#1]
Hi Pavel Alekseyev,
I wonder if you have the package \* Pgmodeler rpm pgModeler 0.8.0.

I downloaded version 0.7.1-2, it's just not compatible with PostgreSQL 9.4
Downloaded the address below.
http://hubbitus.info/rpm/Fedora20/pgmodeler/i686/

Thank you

Edson

**Comment by Hubbitus** [comment]
Edson, could you please test that build?

**Comment by Hubbitus** [comment]
http://hubbitus.info/wiki/Blog:Pgmodeler_update_to_0.8.0

**Comment by Hubbitus** [comment]
I think problem resolved. Please reopen if you steel have troubles or questions regard that.

**Comment by elidorio** [comment]
Hi Pavel,

I did the installation and this presented a problem at startup, as annex.

Unable to load one or more configuration files! Please, check whether the files exist in the folder settings and whether the same are not corrupted so that this error is not repeated on the next boot.

![captura de tela de 2015-03-04 21 13 08](https://cloud.githubusercontent.com/assets/2966579/6496605/8e6327c0-c2b4-11e4-9f49-66052cf46fc0.png)
![captura de tela de 2015-03-04 21 17 45](https://cloud.githubusercontent.com/assets/2966579/6496606/8e6994fc-c2b4-11e4-87c1-3185fe3567ae.png)

**Comment by Hubbitus** [comment]
Does:
rm -rf ~/.config/pgmodeler
helps?

05.03.2015 03:22, Edson Ferreira пишет:

> Hi Pavel,
> 
> I did the installation and this presented a problem at startup, as annex.
> 
> Unable to load one or more configuration files! Please, check whether
> the files exist in the folder settings and whether the same are not
> corrupted so that this error is not repeated on the next boot.
> 
> captura de tela de 2015-03-04 21 13 08
> https://cloud.githubusercontent.com/assets/2966579/6496605/8e6327c0-c2b4-11e4-9f49-66052cf46fc0.png
> captura de tela de 2015-03-04 21 17 45
> https://cloud.githubusercontent.com/assets/2966579/6496606/8e6994fc-c2b4-11e4-87c1-3185fe3567ae.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Hubbitus/Fedora-packaging/issues/1#issuecomment-77280970.

## 

С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru

**Comment by Hubbitus** [comment]
Good evening.

Sorry, I do not understand. Are you speaking about twice present items in menu?

pgmodeler and pGmodeler, last on run said can't find «/usr/bin/start-pgmodeler.sh»?

06.03.2015 21:22, Edson F. Lidorio wrote:

> Are PgModeler icons
> 
> Em 2015-03-06 13:57, Pavel Alexeev escreveu:
> 
> > 06.03.2015 19:05, Edson F. Lidorio пишет:
> > 
> > > Hello Pavél,
> > > 
> > > Now this ok.
> > > Good to known.
> > > 
> > > Note: only thing I find odd, 2 Pgmodeler's icons appears.
> > > Appears the icons (pgmodeler and pgModeler)
> > > About what icons are you speaking?

**Comment by Hubbitus** [comment]
In what annex?
Could you take screenshot?

07.03.2015 21:08, Edson F. Lidorio пишет:

> Good afternoonPavel,
> 
> 2PgModelershortcutsappearsasannex.
> 
> On 07-03-2015 14:56, Pavel Alexeev wrote:
> 
> > Good evening.
> > 
> > Sorry, I do not understand. Are you speaking about twice present
> > items in menu?
> > 
> > pgmodeler and pGmodeler, last on run said can't find
> > «/usr/bin/start-pgmodeler.sh»?
> > 
> > 06.03.2015 21:22, Edson F. Lidorio wrote:
> > 
> > > ArePgModelericons
> > > 
> > > Em 2015-03-06 13:57, Pavel Alexeev escreveu:
> > > 
> > > > 06.03.2015 19:05, Edson F. Lidorio пишет:
> > > > 
> > > > > HelloPavél,
> > > > > 
> > > > > Nowthisok.
> > > > > Good to known.
> > > > > 
> > > > > Note: onlythingI findodd,2Pgmodeler'siconsappears.
> > > > > Appearsthe icons(pgmodelerandpgModeler)
> > > > > About what icons are you speaking?
> > > > > 
> > > > > Moreofthisok.
> > > > > 
> > > > > []'s
> > > > > Edson
> > > > > 
> > > > > On 06-03-2015 09:44, Pavel Alexeev wrote:
> > > > > 
> > > > > > Does:
> > > > > > rm -rf ~/.config/pgmodeler
> > > > > > helps?
> > > > > > 
> > > > > > I also answer in github issue. I think it will be good continue
> > > > > > speak in issue only, to do not double answers.
> > > > > > 
> > > > > > 05.03.2015 03:19, Edson F. Lidorio пишет:
> > > > > > 
> > > > > > > HiPavel,
> > > > > > > 
> > > > > > > I didthe installationandthispresenteda problemat startup,asannex.
> > > > > > > 
> > > > > > > Unable to loadone or moreconfiguration files!Please,checkwhether
> > > > > > > the filesexistin the foldersettings andwhetherthe sameare not
> > > > > > > corruptedso thatthis erroris not repeatedon the next boot.
> > > > > > > 
> > > > > > > On 04-03-2015 13:25, Pavel Alexeev wrote:
> > > > > > > 
> > > > > > > > As always you should satisfy all dependencies.
> > > > > > > > 
> > > > > > > > Most easy way:
> > > > > > > > su -c 'rpm -Uhv http://hubbi
> > > > > > > >  t
> > > > > > > > us.info/rpm/Fedora20/Hubbitus-release-20-1.noarch.rpm'
> > > > > > > > su -c 'yum install pgmodeler'
> > > > > > > > 
> > > > > > > > 04.03.2015 19:13, Edson F. Lidorio пишет:
> > > > > > > > 
> > > > > > > > > HiPavel,
> > > > > > > > > Still didn't work, I need to resolve these dependencies below:
> > > > > > > > > 
> > > > > > > > > sudo rpm -ivh pgmodeler-devel-0.8.0-1.fc20.i686.rpm
> > > > > > > > > erro: Dependências não satisfeitas:
> > > > > > > > >     libobjrenderer.so.1 é requerido por
> > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > >     libparsers.so.1 é requerido por
> > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > >     libpgconnector.so.1 é requerido por
> > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > >     libpgmodeler.so.1 é requerido por
> > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > >     libpgmodeler_ui.so.1 é requerido por
> > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > >     libutils.so.1 é requerido por
> > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > >     pgmodeler(x86-32) = 0.8.0-1.fc20 é requerido por
> > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > 
> > > > > > > > > elidorio@Fedora-21-note pgmodeler]$ rpm -aid
> > > > > > > > > pgmodeler-0.8.0-1.fc20.i686.rpm
> > > > > > > > > erro: Dependências não satisfeitas:
> > > > > > > > >     libQt5Core.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > >     libQt5Gui.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > >     libQt5Network.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > >     libQt5PrintSupport.so.5 é requerido por
> > > > > > > > > pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > >     libQt5Widgets.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > >     libpq.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > > [elidorio@Fedora-21-note pgmodeler]$
> > > > > > > > > 
> > > > > > > > > On 04-03-2015 12:14, Pavel Alexeev wrote:
> > > > > > > > > 
> > > > > > > > > > Hello Edson.
> > > > > > > > > > 
> > > > > > > > > > Did you tested new version
> > > > > > > > > > https://github.com/Hubbitus/Fedora-packaging/issues/1 ?
> > > > > > > > > > 
> > > > > > > > > > 01.03.2015 22:29, Edson F. Lidorio пишет:
> > > > > > > > > > 
> > > > > > > > > > > HiPavelAlekseyev,
> > > > > > > > > > > I wonder if you havethe package*PgmodelerrpmpgModeler0.8.0.
> > > > > > > > > > > I downloaded version0.7.1-2,it's just notcompatiblewith
> > > > > > > > > > > PostgreSQL9.4
> > > > > > > > > > > Downloaded theaddress below.
> > > > > > > > > > > http://hubbitus.info/rpm/Fedora20/pgmodeler/i686/
> > > > > > > > > > > 
> > > > > > > > > > > Thank you
> > > > > > > > > > > 
> > > > > > > > > > > Edson
> > > > > > > > > > 
> > > > > > > > > > ## 
> > > > > > > > > > 
> > > > > > > > > > With best wishes, Pavel Alexeev (aka Pahan-Hubbitus). For
> > > > > > > > > > fast contact with me use jabber: Hubbitus@jabber.ru
> > > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > > > > > > > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > > > > > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru
> > > > 
> > > > ## 
> > > > 
> > > > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > > > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru
> > > 
> > > ## 
> > > 
> > > Edson F. Lidorio
> > > 
> > > Atenção: Este e-mail pode conter anexos no formato ODF (Open Document
> > > Format)/ABNT (extensões odt, ods, odp, odb, odg). Antes de pedir os anexos
> > > em outro formato, você pode instalar gratuita e livremente o LibreOffice (
> > > http://pt-br.libreoffice.org/).
> > 
> > ## 
> > 
> > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru

## 

С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru

**Comment by Hubbitus** [comment]
07.03.2015 21:19, Edson F. Lidorio пишет:

> In annex.

![captura de tela de 2015-03-07 15 01 58](https://cloud.githubusercontent.com/assets/720349/6545076/e0af222c-c584-11e4-9f7f-c2ffca3bef59.png)

> On 07-03-2015 15:11, Pavel Alexeev wrote:
> 
> > In what annex?
> > Could you take screenshot?
> > 
> > 07.03.2015 21:08, Edson F. Lidorio пишет:
> > 
> > > Good afternoonPavel,
> > > 
> > > 2PgModelershortcutsappearsasannex.
> > > 
> > > On 07-03-2015 14:56, Pavel Alexeev wrote:
> > > 
> > > > Good evening.
> > > > 
> > > > Sorry, I do not understand. Are you speaking about twice present
> > > > items in menu?
> > > > 
> > > > pgmodeler and pGmodeler, last on run said can't find
> > > > «/usr/bin/start-pgmodeler.sh»?
> > > > 
> > > > 06.03.2015 21:22, Edson F. Lidorio wrote:
> > > > 
> > > > > ArePgModelericons
> > > > > 
> > > > > Em 2015-03-06 13:57, Pavel Alexeev escreveu:
> > > > > 
> > > > > > 06.03.2015 19:05, Edson F. Lidorio пишет:
> > > > > > 
> > > > > > > HelloPavél,
> > > > > > > 
> > > > > > > Nowthisok.
> > > > > > > Good to known.
> > > > > > > 
> > > > > > > Note: onlythingI findodd,2Pgmodeler'siconsappears.
> > > > > > > Appearsthe icons(pgmodelerandpgModeler)
> > > > > > > About what icons are you speaking?
> > > > > > > 
> > > > > > > Moreofthisok.
> > > > > > > 
> > > > > > > []'s
> > > > > > > Edson
> > > > > > > 
> > > > > > > On 06-03-2015 09:44, Pavel Alexeev wrote:
> > > > > > > 
> > > > > > > > Does:
> > > > > > > > rm -rf ~/.config/pgmodeler
> > > > > > > > helps?
> > > > > > > > 
> > > > > > > > I also answer in github issue. I think it will be good continue
> > > > > > > > speak in issue only, to do not double answers.
> > > > > > > > 
> > > > > > > > 05.03.2015 03:19, Edson F. Lidorio пишет:
> > > > > > > > 
> > > > > > > > > HiPavel,
> > > > > > > > > 
> > > > > > > > > I didthe installationandthispresenteda problemat startup,asannex.
> > > > > > > > > 
> > > > > > > > > Unable to loadone or moreconfiguration
> > > > > > > > > files!Please,checkwhether the filesexistin the foldersettings
> > > > > > > > > andwhetherthe sameare not corruptedso thatthis erroris not
> > > > > > > > > repeatedon the next boot.
> > > > > > > > > 
> > > > > > > > > On 04-03-2015 13:25, Pavel Alexeev wrote:
> > > > > > > > > 
> > > > > > > > > > As always you should satisfy all dependencies.
> > > > > > > > > > 
> > > > > > > > > > Most easy way:
> > > > > > > > > > su -c 'rpm -Uhv http://hubbi
> > > > > > > > > >  t
> > > > > > > > > > us.info/rpm/Fedora20/Hubbitus-release-20-1.noarch.rpm'
> > > > > > > > > > su -c 'yum install pgmodeler'
> > > > > > > > > > 
> > > > > > > > > > 04.03.2015 19:13, Edson F. Lidorio пишет:
> > > > > > > > > > 
> > > > > > > > > > > HiPavel,
> > > > > > > > > > > Still didn't work, I need to resolve these dependencies below:
> > > > > > > > > > > 
> > > > > > > > > > > sudo rpm -ivh pgmodeler-devel-0.8.0-1.fc20.i686.rpm
> > > > > > > > > > > erro: Dependências não satisfeitas:
> > > > > > > > > > >     libobjrenderer.so.1 é requerido por
> > > > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > > >     libparsers.so.1 é requerido por
> > > > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > > >     libpgconnector.so.1 é requerido por
> > > > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > > >     libpgmodeler.so.1 é requerido por
> > > > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > > >     libpgmodeler_ui.so.1 é requerido por
> > > > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > > >     libutils.so.1 é requerido por
> > > > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > > >     pgmodeler(x86-32) = 0.8.0-1.fc20 é requerido por
> > > > > > > > > > > pgmodeler-devel-0.8.0-1.fc20.i686
> > > > > > > > > > > 
> > > > > > > > > > > elidorio@Fedora-21-note pgmodeler]$ rpm -aid
> > > > > > > > > > > pgmodeler-0.8.0-1.fc20.i686.rpm
> > > > > > > > > > > erro: Dependências não satisfeitas:
> > > > > > > > > > >     libQt5Core.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > > > >     libQt5Gui.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > > > >     libQt5Network.so.5 é requerido por
> > > > > > > > > > > pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > > > >     libQt5PrintSupport.so.5 é requerido por
> > > > > > > > > > > pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > > > >     libQt5Widgets.so.5 é requerido por
> > > > > > > > > > > pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > > > >     libpq.so.5 é requerido por pgmodeler-0.8.0-1.fc20.i686
> > > > > > > > > > > [elidorio@Fedora-21-note pgmodeler]$
> > > > > > > > > > > 
> > > > > > > > > > > On 04-03-2015 12:14, Pavel Alexeev wrote:
> > > > > > > > > > > 
> > > > > > > > > > > > Hello Edson.
> > > > > > > > > > > > 
> > > > > > > > > > > > Did you tested new version
> > > > > > > > > > > > https://github.com/Hubbitus/Fedora-packaging/issues/1 ?
> > > > > > > > > > > > 
> > > > > > > > > > > > 01.03.2015 22:29, Edson F. Lidorio пишет:
> > > > > > > > > > > > 
> > > > > > > > > > > > > HiPavelAlekseyev,
> > > > > > > > > > > > > I wonder if you havethe package*PgmodelerrpmpgModeler0.8.0.
> > > > > > > > > > > > > I downloaded version0.7.1-2,it's just notcompatiblewith
> > > > > > > > > > > > > PostgreSQL9.4
> > > > > > > > > > > > > Downloaded theaddress below.
> > > > > > > > > > > > > http://hubbitus.info/rpm/Fedora20/pgmodeler/i686/
> > > > > > > > > > > > > 
> > > > > > > > > > > > > Thank you
> > > > > > > > > > > > > 
> > > > > > > > > > > > > Edson
> > > > > > > > > > > > 
> > > > > > > > > > > > ## 
> > > > > > > > > > > > 
> > > > > > > > > > > > With best wishes, Pavel Alexeev (aka Pahan-Hubbitus). For
> > > > > > > > > > > > fast contact with me use jabber: Hubbitus@jabber.ru
> > > > > > > > > > 
> > > > > > > > > > ## 
> > > > > > > > > > 
> > > > > > > > > > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > > > > > > > > > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru
> > > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > > > > > > > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > > > > > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Edson F. Lidorio
> > > > > 
> > > > > Atenção: Este e-mail pode conter anexos no formato ODF (Open Document
> > > > > Format)/ABNT (extensões odt, ods, odp, odb, odg). Antes de pedir os anexos
> > > > > em outro formato, você pode instalar gratuita e livremente o LibreOffice (
> > > > > http://pt-br.libreoffice.org/).
> > > > 
> > > > ## 
> > > > 
> > > > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > > > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru
> > 
> > ## 
> > 
> > С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
> > Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru

## 

С уважением, Павел Алексеев (aka Pahan-Hubbitus).  
Для быстрой связи со мной используйте джаббер. Мой JID: Hubbitus@jabber.ru

**Comment by Hubbitus** [comment]
Thank you Edson F. Lidorio.
That issue reported to upstream author: https://github.com/pgmodeler/pgmodeler/issues/633. And I hope will be resolved soon.

**Comment by elidorio** [comment]
HiPavel,

Thank you for yourcontributions.
