### ISSUE TITLE
gimp-gap freeworld

### ISSUE THREAD

**Issue by cmirnow** [Hubbitus/Fedora-packaging#2]
I think, it's very nice idea - gimp-gap freeworld! Do it, please. This will give me the opportunity to create a variety of landmark images. ))

**Comment by Hubbitus** [comment]
http://hubbitus.info/wiki/Blog:Fedora:_new_package_gimp-gap-freeworld

It should be fixed now. Please reopen if needed.

**Comment by cmirnow** [comment]
http://hubbitus.info/wiki/Blog:Fedora:_new_package_gimp-gap-freeworld

Forbidden

You don't have permission to access /wiki/Blog:Fedora:_new_package_gimp-gap-freeworld on this server.

**Comment by Hubbitus** [comment]
I'm very sorry. It was issue with my hoster. Site moved now to another server. For rpm repo added mirror URL. Please check it again.
