### ISSUE TITLE
Copr?

### ISSUE THREAD

**Issue by bysshe** [Hubbitus/Fedora-packaging#4]
Hi,

Have you considered using the copr tool to both build and distribute this kernel?

**Comment by Hubbitus** [comment]
I use copr for example for Remmina builds. Does it have some advantages for you in another format of repository?

**Comment by Hubbitus** [comment]
Closing as there no answer long time...

**Comment by Hubbitus** [comment]
@bysshe please reopen or comment if it will have any advantages at least for you.

**Comment by bysshe** [comment]
Hi @Hubbitus,

I didn't notice that you had responded to this, so I'm sorry for responding so tardily.
I run Fedora, so my only concern is being able to install, and keep updated, your kernel for my distribution.
Is this the kind of information you were looking for?

**Comment by Hubbitus** [comment]
Then my repository http://hubbitus.info/wiki/Repository should solve that problem. Is not?
